### ISSUE TITLE
Missing friendly-errors-webpack-plugin?

### ISSUE THREAD

**Issue by krsyoung** [quasarframework/quasar-play#9]
Hey, just checking if this is needed or not?  This is based off of a fresh clone today.

```
quasar-play user$ quasar dev ios


> quasar-play@0.13.2 dev /Users/user/Development/quasar-play
> node build/script.dev.js "ios"

module.js:471
    throw err;
    ^

Error: Cannot find module 'friendly-errors-webpack-plugin'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/user/Development/quasar-play/build/webpack.dev.conf.js:8:26)
```

I was able to get around the error by running:

```
npm install --save-dev friendly-errors-webpack-plugin
```

**Comment by rstoenescu** [comment]
Hmm, that doesn't seem to be fresh. It should say `quasar-play@0.13.6`. Notice the ending `6` there.
